name: feature_flags
description: A Flutter package to manage feature flagging.
version: 0.1.3
homepage: https://github.com/aloisdeniel/feature_flags

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: